#!/usr/bin/env node
// autotune evaluator — the read-only ground truth (prepare.py analog).
//
// Calls the REAL matcher (lib/workers/skills.js) against the frozen eval sets.
// No LLM, no network — deterministic and fast, so accuracy is a clean
// keep/discard signal for the tuning loop.
//
// Reports:
//   train   — accuracy over eval.json (sets: exam + hard). THIS is what the loop optimizes.
//   holdout — accuracy over eval.holdout.json (the loop must not see these). Overfitting check.
//   kwChars — total curated-keyword characters across all skills (lower = simpler).
//
// Usage:
//   node skills/autotune/score.mjs            human-readable report
//   node skills/autotune/score.mjs --json     machine-readable
//   node skills/autotune/score.mjs --log keep --desc "..."   append a ledger row
//
// Do NOT edit this file or the eval*.json files during a tuning run — they are the metric.

import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { readFileSync, existsSync, appendFileSync, mkdirSync } from "node:fs";
import { execSync } from "node:child_process";
import { loadSkillIndex, matchSkills } from "../../lib/workers/skills.js";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..", "..");
const LIMIT = 12; // pull more than default 3 so expectNot can't hide a leaked stub

const readJson = p => JSON.parse(readFileSync(p, "utf-8"));
const index = loadSkillIndex(join(repoRoot, "skills"));

function judge(cases) {
  let correct = 0;
  const fails = [];
  for (const c of cases) {
    const got = matchSkills(c.prompt, index, { limit: LIMIT }).map(s => s.name);
    const ok = c.expect ? got[0] === c.expect : !c.expectNot.some(n => got.includes(n));
    if (ok) correct++;
    else fails.push({ id: c.id, expect: c.expect ?? `NOT ${c.expectNot.join("/")}`, got, prompt: c.prompt });
  }
  return { correct, total: cases.length, fails };
}

const all = readJson(join(here, "eval.json")).cases;
const train = judge(all);
const bySet = set => judge(all.filter(c => c.set === set));
const exam = bySet("exam");
const hard = bySet("hard");

const holdoutPath = join(here, "eval.holdout.json");
const holdout = existsSync(holdoutPath) ? judge(readJson(holdoutPath).cases) : null;

const kwChars = index.reduce((n, s) => n + (s.keywords?.length ?? 0), 0);
const acc = r => +(r.correct / r.total).toFixed(4);

const result = {
  train: acc(train), holdout: holdout ? acc(holdout) : null, kwChars,
  breakdown: {
    exam: `${exam.correct}/${exam.total}`,
    hard: `${hard.correct}/${hard.total}`,
    holdout: holdout ? `${holdout.correct}/${holdout.total}` : "—",
  },
  fails: train.fails,
  holdoutFails: holdout ? holdout.fails : [],
};

// --log <status> --desc "..."  → append a well-formed ledger row (no hand-formatted TSV).
const logIdx = process.argv.indexOf("--log");
if (logIdx !== -1) {
  const status = process.argv[logIdx + 1] ?? "?";
  const descIdx = process.argv.indexOf("--desc");
  const desc = (descIdx !== -1 ? process.argv[descIdx + 1] : "").replace(/\t|\n/g, " ");
  // `branch` is the session id — each tuning run is its own `autotune/<tag>` branch,
  // so the ledger row tells you which run produced it. `ts` orders rows across runs.
  const git = cmd => { try { return execSync(cmd, { cwd: repoRoot }).toString().trim(); } catch { return "—"; } };
  const commit = git("git rev-parse --short HEAD");
  const branch = git("git rev-parse --abbrev-ref HEAD");
  const ts = new Date().toISOString();
  // Ledger lives under var/ (gitignored runtime dir) — a persistent record, invisible to git.
  const ledgerDir = join(repoRoot, "var", "autotune");
  const ledger = join(ledgerDir, "results.tsv");
  mkdirSync(ledgerDir, { recursive: true });
  if (!existsSync(ledger)) appendFileSync(ledger, "ts\tbranch\tcommit\ttrain_acc\tholdout_acc\tkw_chars\tstatus\tdescription\n");
  appendFileSync(ledger, `${ts}\t${branch}\t${commit}\t${result.train}\t${result.holdout ?? "—"}\t${kwChars}\t${status}\t${desc}\n`);
  console.log(`logged → ${ledger}  (branch ${branch})`);
}

if (process.argv.includes("--json")) {
  console.log(JSON.stringify(result, null, 2));
} else {
  console.log(`train:   ${result.train}  [exam ${result.breakdown.exam}, hard ${result.breakdown.hard}]`);
  console.log(`holdout: ${result.holdout ?? "—"}  [${result.breakdown.holdout}]   (not optimized — overfitting check)`);
  console.log(`kwChars: ${kwChars}`);
  const show = (label, fails) => {
    if (!fails.length) return;
    console.log(`\n${label}:`);
    for (const f of fails) {
      console.log(`  [${f.id}] expect ${f.expect}  got [${f.got.join(", ") || "—"}]`);
      console.log(`         "${f.prompt}"`);
    }
  };
  show("train failures", train.fails);
  show("holdout failures", result.holdoutFails);
  if (!train.fails.length && !result.holdoutFails.length) console.log("\nall cases pass ✅");
}
